import { NextResponse } from 'next/server';

export async function GET() {
  const mealOptions = [
    {
      value: 'Apple',
      label: 'Apple (piece)',
      amount: 1,
      measure: 'piece',
      cal: 52,
      protein: 0.3,
      carbs: 14,
      fat: 0.2,
      base: 100,
      selection: {
        amount: 1,
        protein: 0.3,
        carbs: 14,
        fat: 0.2,
        cal: 52,
      },
    },
    {
      value: 'Banana',
      label: 'Banana (piece)',
      amount: 1,
      measure: 'piece',
      cal: 89,
      protein: 1.1,
      carbs: 23,
      fat: 0.3,
      base: 100,
      selection: {
        amount: 1,
        protein: 1.1,
        carbs: 23,
        fat: 0.3,
        cal: 89,
      },
    },
    {
      value: 'Broccoli',
      label: 'Broccoli (gr)',
      amount: 100,
      measure: 'gr',
      cal: 34,
      protein: 2.8,
      carbs: 6,
      fat: 0.4,
      base: 100,
      selection: {
        amount: 100,
        protein: 2.8,
        carbs: 6,
        fat: 0.4,
        cal: 34,
      },
    },
    {
      value: 'Carrot',
      label: 'Carrot (gr)',
      amount: 100,
      measure: 'gr',
      cal: 41,
      protein: 0.9,
      carbs: 10,
      fat: 0.2,
      base: 100,
      selection: {
        amount: 100,
        protein: 0.9,
        carbs: 10,
        fat: 0.2,
        cal: 41,
      },
    },
    {
      value: 'Chicken Breast',
      label: 'Chicken Breast (gr)',
      amount: 100,
      measure: 'gr',
      cal: 165,
      protein: 31,
      carbs: 0,
      fat: 3.6,
      base: 100,
      selection: {
        amount: 100,
        protein: 31,
        carbs: 0,
        fat: 3.6,
        cal: 165,
      },
    },
    {
      value: 'Eggs',
      label: 'Eggs (piece)',
      amount: 2,
      measure: 'piece',
      cal: 140,
      protein: 12,
      carbs: 1,
      fat: 10,
      base: 100,
      selection: {
        amount: 2,
        protein: 12,
        carbs: 1,
        fat: 10,
        cal: 140,
      },
    },
    {
      value: 'Oatmeal',
      label: 'Oatmeal (bowl)',
      amount: 1,
      measure: 'bowl',
      cal: 150,
      protein: 5,
      carbs: 27,
      fat: 2.5,
      base: 100,
      selection: {
        amount: 1,
        protein: 5,
        carbs: 27,
        fat: 2.5,
        cal: 150,
      },
    },
    {
      value: 'Grilled Chicken',
      label: 'Grilled Chicken (breast)',
      amount: 1,
      measure: 'breast',
      cal: 165,
      protein: 31,
      carbs: 0,
      fat: 3.5,
      base: 100,
      selection: {
        amount: 1,
        protein: 31,
        carbs: 0,
        fat: 3.5,
        cal: 165,
      },
    },
    {
      value: 'Salmon',
      label: 'Salmon (fillet)',
      amount: 1,
      measure: 'fillet',
      cal: 280,
      protein: 39,
      carbs: 0,
      fat: 12,
      base: 100,
      selection: {
        amount: 1,
        protein: 39,
        carbs: 0,
        fat: 12,
        cal: 280,
      },
    },
    {
      value: 'Greek Salad',
      label: 'Greek Salad (bowl)',
      amount: 1,
      measure: 'bowl',
      cal: 190,
      protein: 7,
      carbs: 10,
      fat: 15,
      base: 100,
      selection: {
        amount: 1,
        protein: 7,
        carbs: 10,
        fat: 15,
        cal: 190,
      },
    },
    {
      value: 'Steak',
      label: 'Steak (sirloin)',
      amount: 1,
      measure: 'sirloin',
      cal: 350,
      protein: 25,
      carbs: 0,
      fat: 27,
      base: 100,
      selection: {
        amount: 1,
        protein: 25,
        carbs: 0,
        fat: 27,
        cal: 350,
      },
    },
    {
      value: 'Tuna Sandwich',
      label: 'Tuna Sandwich (piece)',
      amount: 1,
      measure: 'piece',
      cal: 450,
      protein: 24,
      carbs: 45,
      fat: 19,
      base: 100,
      selection: {
        amount: 1,
        protein: 24,
        carbs: 45,
        fat: 19,
        cal: 450,
      },
    },
    {
      value: 'Pizza',
      label: 'Pizza (slice)',
      amount: 1,
      measure: 'slice',
      cal: 285,
      protein: 13.3,
      carbs: 30,
      fat: 12.5,
      base: 100,
      selection: {
        amount: 1,
        protein: 13.3,
        carbs: 30,
        fat: 12.5,
        cal: 285,
      },
    },
    {
      value: 'Burger',
      label: 'Burger (piece)',
      amount: 1,
      measure: 'piece',
      cal: 300,
      protein: 13,
      carbs: 30,
      fat: 16,
      base: 100,
      selection: {
        amount: 1,
        protein: 13,
        carbs: 30,
        fat: 16,
        cal: 300,
      },
    },
    {
      value: 'Taco',
      label: 'Taco (piece)',
      amount: 1,
      measure: 'piece',
      cal: 170,
      protein: 6,
      carbs: 17,
      fat: 9,
      base: 100,
      selection: {
        amount: 1,
        protein: 6,
        carbs: 17,
        fat: 9,
        cal: 170,
      },
    },
    {
      value: 'Spaghetti',
      label: 'Spaghetti (plate)',
      amount: 1,
      measure: 'plate',
      cal: 221,
      protein: 8,
      carbs: 43,
      fat: 1.5,
      base: 100,
      selection: {
        amount: 1,
        protein: 8,
        carbs: 43,
        fat: 1.5,
        cal: 221,
      },
    },
    {
      value: 'Sushi',
      label: 'Sushi (roll)',
      amount: 1,
      measure: 'roll',
      cal: 50,
      protein: 2,
      carbs: 8,
      fat: 1,
      base: 100,
      selection: {
        amount: 1,
        protein: 2,
        carbs: 8,
        fat: 1,
        cal: 50,
      },
    },
    {
      value: 'Fajitas',
      label: 'Fajitas (serving)',
      amount: 1,
      measure: 'serving',
      cal: 400,
      protein: 25,
      carbs: 25,
      fat: 20,
      base: 100,
      selection: {
        amount: 1,
        protein: 25,
        carbs: 25,
        fat: 20,
        cal: 400,
      },
    },
    {
      value: 'Hotdog',
      label: 'Hotdog (piece)',
      amount: 1,
      measure: 'piece',
      cal: 150,
      protein: 5,
      carbs: 18,
      fat: 6,
      base: 100,
      selection: {
        amount: 1,
        protein: 5,
        carbs: 18,
        fat: 6,
        cal: 150,
      },
    },
    {
      value: 'Fried Chicken',
      label: 'Fried Chicken (piece)',
      amount: 1,
      measure: 'piece',
      cal: 135,
      protein: 13,
      carbs: 6,
      fat: 7,
      base: 100,
      selection: {
        amount: 1,
        protein: 13,
        carbs: 6,
        fat: 7,
        cal: 135,
      },
    },
    {
      value: 'Spaghetti Bolognese',
      label: 'Spaghetti Bolognese (serving)',
      amount: 1,
      measure: 'serving',
      cal: 520,
      protein: 22,
      carbs: 62,
      fat: 19,
      base: 100,
      selection: {
        amount: 1,
        protein: 22,
        carbs: 62,
        fat: 19,
        cal: 520,
      },
    },
    {
      value: 'Beef Burger',
      label: 'Beef Burger (piece)',
      amount: 1,
      measure: 'burger',
      cal: 500,
      protein: 26,
      carbs: 40,
      fat: 28,
      base: 100,
      selection: {
        amount: 1,
        protein: 26,
        carbs: 40,
        fat: 28,
        cal: 500,
      },
    },
    {
      value: 'Chicken Wrap',
      label: 'Chicken Wrap (piece)',
      amount: 1,
      measure: 'wrap',
      cal: 300,
      protein: 17,
      carbs: 33,
      fat: 10,
      base: 100,
      selection: {
        amount: 1,
        protein: 17,
        carbs: 33,
        fat: 10,
        cal: 300,
      },
    },
  ];

  return NextResponse.json({ mealOptions });
}
