import { NextResponse } from 'next/server';

export async function GET() {
  const meals = [
    {
      value: 'Fried Eggs',
      label: 'Fried Eggs (piece)',
      amount: 1,
      measure: 'piece',
      cal: 122,
      protein: 6.4,
      carbs: 1.04,
      fat: 10.34,
      base: 1,
      selection: {
        amount: 1,
        cal: 122,
        protein: 6.4,
        carbs: 1.04,
        fat: 10.34,
      },
    },
    {
      value: 'Oatmeal',
      label: 'Oatmeal (gr)',
      amount: 100,
      measure: 'gram',
      cal: 351,
      protein: 11.35,
      carbs: 57.25,
      fat: 25.8,
      base: 100,
      selection: {
        amount: 100,
        cal: 351,
        protein: 11.35,
        carbs: 57.25,
        fat: 25.8,
      },
    },
    {
      value: 'Eggs',
      label: 'Eggs (piece)',
      amount: 1,
      measure: 'piece',
      cal: 78,
      protein: 6.29,
      carbs: 0.56,
      fat: 5.31,
      base: 1,
      selection: {
        amount: 1,
        cal: 78,
        protein: 6.29,
        carbs: 0.56,
        fat: 5.31,
      },
    },
    {
      value: 'Olives',
      label: 'Olives (piece)',
      amount: 1,
      measure: 'piece',
      cal: 8,
      protein: 0.07,
      carbs: 0.04,
      fat: 0.84,
      base: 1,
      selection: {
        amount: 1,
        cal: 8,
        protein: 0.07,
        carbs: 0.04,
        fat: 0.84,
      },
    },
    {
      value: 'Curd Cheese',
      label: 'Curd Cheese (gr)',
      amount: 100,
      measure: 'gram',
      cal: 60,
      protein: 3.24,
      carbs: 4.74,
      fat: 3.24,
      base: 100,
      selection: {
        amount: 100,
        cal: 60,
        protein: 3.24,
        carbs: 4.74,
        fat: 3.24,
      },
    },
    {
      value: 'Avocado',
      label: 'Avocado (quarter piece)',
      amount: 1,
      measure: 'piece',
      cal: 56,
      protein: 0.7,
      carbs: 2.99,
      fat: 5.13,
      base: 1,
      selection: {
        amount: 1,
        cal: 56,
        protein: 0.7,
        carbs: 2.99,
        fat: 5.13,
      },
    },
    {
      value: 'Chicken Brest',
      label: 'Chicken Brest (gr)',
      amount: 100,
      measure: 'gram',
      cal: 115,
      protein: 26.8,
      carbs: 0,
      fat: 0.7,
      base: 100,
      selection: {
        amount: 100,
        cal: 115,
        protein: 26.8,
        carbs: 0,
        fat: 0.7,
      },
    },
    {
      value: 'Rice',
      label: 'Rice (gr)',
      amount: 100,
      measure: 'gram',
      cal: 171,
      protein: 3.16,
      carbs: 30.69,
      fat: 3.74,
      base: 100,
      selection: {
        amount: 100,
        cal: 171,
        protein: 3.16,
        carbs: 30.69,
        fat: 3.74,
      },
    },
    {
      value: 'Pasta',
      label: 'Pasta (gr)',
      amount: 100,
      measure: 'gram',
      cal: 157,
      protein: 5.8,
      carbs: 30.59,
      fat: 0.93,
      base: 100,
      selection: {
        amount: 100,
        cal: 157,
        protein: 5.8,
        carbs: 30.59,
        fat: 0.93,
      },
    },
    {
      value: 'Yoghurt',
      label: 'Yoghurt (spoon)',
      amount: 1,
      measure: 'spoon',
      cal: 27,
      protein: 1.56,
      carbs: 2.1,
      fat: 1.46,
      base: 1,
      selection: {
        amount: 1,
        cal: 27,
        protein: 1.56,
        carbs: 2.1,
        fat: 1.46,
      },
    },
    {
      value: 'Tuna',
      label: 'Tuna (gr)',
      amount: 100,
      measure: 'gram',
      cal: 174,
      protein: 17.26,
      carbs: 0,
      fat: 11.77,
      base: 100,
      selection: {
        amount: 100,
        cal: 174,
        protein: 17.26,
        carbs: 0,
        fat: 11.77,
      },
    },
    {
      value: 'Ezine Cheese',
      label: 'Ezine Cheese (gr)',
      amount: 100,
      measure: 'gram',
      cal: 309,
      protein: 18.22,
      carbs: 3.05,
      fat: 24.88,
      base: 100,
      selection: {
        amount: 100,
        cal: 309,
        protein: 18.22,
        carbs: 3.05,
        fat: 24.88,
      },
    },
    {
      value: 'Labne Cheese',
      label: 'Labne Cheese (gr)',
      amount: 100,
      measure: 'gram',
      cal: 200,
      protein: 5.0,
      carbs: 5.5,
      fat: 18.0,
      base: 100,
      selection: {
        amount: 100,
        cal: 200,
        protein: 5.0,
        carbs: 5.5,
        fat: 18.0,
      },
    },
    {
      value: 'Cucumber',
      label: 'Cucumber (piece)',
      amount: 1,
      measure: 'piece',
      cal: 18,
      protein: 0.78,
      carbs: 4.36,
      fat: 0.13,
      base: 1,
      selection: {
        amount: 1,
        cal: 18,
        protein: 0.78,
        carbs: 4.36,
        fat: 0.13,
      },
    },
    {
      value: 'Tomatoes',
      label: 'Tomatoes (piece)',
      amount: 1,
      measure: 'piece',
      cal: 20,
      protein: 0.97,
      carbs: 4.28,
      fat: 0.22,
      base: 1,
      selection: {
        amount: 1,
        cal: 20,
        protein: 0.97,
        carbs: 4.28,
        fat: 0.22,
      },
    },
    {
      value: 'Chicken Wings',
      label: 'Chicken Wings (piece)',
      amount: 1,
      measure: 'piece',
      cal: 99,
      protein: 9.0,
      carbs: 0,
      fat: 6.99,
      base: 1,
      selection: {
        amount: 1,
        cal: 99,
        protein: 9.0,
        carbs: 0,
        fat: 6.99,
      },
    },
    {
      value: 'Ground Beef',
      label: 'Ground Beef (gr)',
      amount: 100,
      measure: 'gram',
      cal: 202,
      protein: 18.65,
      carbs: 0.46,
      fat: 13.63,
      base: 100,
      selection: {
        amount: 100,
        cal: 202,
        protein: 18.65,
        carbs: 0.46,
        fat: 13.63,
      },
    },
    {
      value: 'Meatballs',
      label: 'Meatballs (piece)',
      amount: 1,
      measure: 'piece',
      cal: 67,
      protein: 5.22,
      carbs: 1.97,
      fat: 4.19,
      base: 1,
      selection: {
        amount: 1,
        cal: 67,
        protein: 5.22,
        carbs: 1.97,
        fat: 4.19,
      },
    },
    {
      value: 'Liver',
      label: 'Liver (gr)',
      amount: 100,
      measure: 'gram',
      cal: 192,
      protein: 28.42,
      carbs: 3.77,
      fat: 6.26,
      base: 100,
      selection: {
        amount: 100,
        cal: 192,
        protein: 28.42,
        carbs: 3.77,
        fat: 6.26,
      },
    },
    {
      value: 'Banana',
      label: 'Banana (piece)',
      amount: 1,
      measure: 'piece',
      cal: 151,
      protein: 1.85,
      carbs: 38.83,
      fat: 0.56,
      base: 1,
      selection: {
        amount: 1,
        cal: 151,
        protein: 1.85,
        carbs: 38.83,
        fat: 0.56,
      },
    },
  ];

  const mealOptions = meals.sort((a, b) => a.value.localeCompare(b.value));

  return NextResponse.json({ mealOptions });
}
